import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";
import NavBar from "@/widgets/Nav/NavBar";
import AuthProvider from "@/shared/lib/AuthProvider/AuthProvider";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.className} min-h-screen   `}>
          <NavBar />
          <main className="flex max-w-7xl m-auto flex-col ">{children}</main>
        </body>
      </AuthProvider>
    </html>
  );
}
